{% set name = "condansis" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6b50f5ee08f4f025db3b0e3944b945a7b6d26e007ee6a2ef93ad9bb3f873dae8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - jinja2
    - nsis
    - conda-pack >=0.5.0

test:
  imports:
    - condansis

about:
  home: https://github.com/guilhermebs/condansis
  summary: Build self-extracting Windows installers for your python app
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt


extra:
  recipe-maintainers:
    - guilhermebs
