{% set name = "condansis" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a4cb9ec5f1714c846d1b9f861053cef7a0ff0ebddc326697e2c130e3bd24ef7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - jinja2
    - nsis
    - conda-pack >=0.5.0

test:
  imports:
    - condansis

about:
  home: https://github.com/guilhermebs/condansis
  summary: Build self-extracting Windows installers for your python app
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt


extra:
  recipe-maintainers:
    - guilhermebs
